spring:
  application:
    name: store
  # mvc:
  #   log-request-details: true
# logging:
#   level:
#     org:
#       springframework:
#         web: DEBUG
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #15m
    refreshTokenExpiration: 604800 #7d
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}