spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: 12345678
  jpa:
    show-sql: true
  mvc:
    log-request-details: true
# logging:
#   level:
#     org:
#       springframework:
#         web: DEBUG
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 #5m
    refreshTokenExpiration: 604800 #7d