spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: 12345678
  jpa:
    show-sql: true
  # mvc:
  #   log-request-details: true
# logging:
#   level:
#     org:
#       springframework:
#         web: DEBUG
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 #2h
    refreshTokenExpiration: 604800 #7d
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:3000